### ISSUE TITLE
adding component to see users

### ISSUE THREAD

**Issue by Debrej** [Debrej/project_a#19]

**Comment by Debrej** [comment]
still need to have a better design, thinking of a scrollable grid of 4 users

**Comment by Debrej** [comment]
after adding a search by name, surname or mail i think it will be nice

**Comment by LeoMouyna** [comment]
In my opinion, you should also have a team filter and probably a way to display that a user is a team supervisor.

**Comment by Debrej** [comment]
I added a filter by team and I'm working on the search I was talking about

**Comment by Debrej** [comment]
searching is working now merging the branch
