### ISSUE TITLE
Improve phone number field component

### ISSUE THREAD

**Issue by LeoMouyna** [Debrej/project_a#20]
**Is your feature request related to a problem? Please describe.**
We can't use international phone number format on user form.

**Describe the solution you'd like**
I would appreciate if a drop down to select my country prefix could be next to my phone number field like in this screen shot:
![image](https://user-images.githubusercontent.com/17725363/72641936-90b0a100-396b-11ea-82e8-91efb23e5559.png)

**Describe alternatives you've considered**
I would like to enter a phone number with the international format +xxx yyyyyyyyy as plain text

**Comment by Debrej** [comment]
this is done, putting it on the demo website right now
