### ISSUE TITLE
Improve map component

### ISSUE THREAD

**Issue by LeoMouyna** [Debrej/project_a#21]
**Is your feature request related to a problem? Please describe.**
When I click somewhere on the map I would like to set coordinates to this new point.

**Describe the solution you'd like**
Add an event listener too click event and set location to the coordinates where the user clicked.
According to leaflet doc it looks like it's possible: https://leafletjs.com/examples/quick-start/#dealing-with-events

**Comment by Debrej** [comment]
this is done, putting it on the demo website right now

**Comment by Debrej** [comment]
there could still be improvement

**Comment by Debrej** [comment]
we need to the possibility to click to move the marker but can still be draggable
