### ISSUE TITLE
support for fuzzy search

### ISSUE THREAD

**Issue by arn-all** [Debrej/project_a#24]
**Is your feature request related to a problem? Please describe.**
When looking up lots of people, typos in names occur very often. It's also difficult to remember the exact name of everybody, and nobody wants to scroll the whole list of volunteers to find someone.

**Describe the solution you'd like**
"Fuzzy search" can be a huge time saver, along with being a fancy feature to demonstrate.
With fuzzy search, you can find long names (e.g indian, persian, ..) by typing the first few letters, even with a mistake. You can also find "Boullanger" by typing "Boulanger".

A possible solution is fuse.js, but there's plenty of solutions for fuzzy search out there 
https://fusejs.io/ 
https://github.com/krisk/Fuse

Performance should not be an issue with the amount of data we'll have to deal with.

**Comment by Debrej** [comment]
supported
