### ISSUE TITLE
Implement translation

### ISSUE THREAD

**Issue by LeoMouyna** [Debrej/project_a#30]
I would be nice if we could support several languages according to user setting.

Here is some nice resources: 

- [vue-i18n](https://kazupon.github.io/vue-i18n/introduction.html)
- [medium article tutorial](https://medium.com/hypefactors/add-i18n-and-manage-translations-of-a-vue-js-powered-website-73b4511ca69c)

It can be a good idea to look at [mobilizon config](https://framagit.org/framasoft/mobilizon/tree/master/js) to check how they deal with translation.

**Comment by Debrej** [comment]
translation implemented in directory i18n
might want to check the spelling
